apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "odk.fullname" . }}-pyxform
    version: "1.12.1"
  name: {{ include "odk.fullname" . }}-pyxform
spec:
  replicas: {{ .Values.pyxform.replicas }}
  selector:
    matchLabels:
      app: {{ include "odk.fullname" . }}-pyxform
  template:
    metadata:
      labels:
        app: {{ include "odk.fullname" . }}-pyxform
    spec:
      containers:
      ## TK 20260309: move this to values.yaml
      ##              but keep default value in the template for backward compatibility
        - name: pyxform
          image: {{ default (printf "%s/pyxform-http:v4.2.0" .Values.image.odkregistry) (printf "%s/%s" .Values.image.odkregistry .Values.pyxform.image) | quote }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.pyxform.resources | nindent 12 }}
      restartPolicy: Always
