USER-SUPPLIED VALUES:
enketo:
  image: ghcr.io/enketo/enketo:7.5.0
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
fullnameOverride: ""
image:
  odkregistry: ghcr.io/getodk
  pullPolicy: IfNotPresent
  registry: docker.io
  tag: ""
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/enable-global-auth: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "25600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "25600"
  className: public
  enabled: true
  hosts:
  - host: odkcentral.k8s.tinonet.nl
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - odkcentral.k8s.tinonet.nl
    secretName: odkcentral.k8s.tinonet.nl
nameOverride: ""
nginx:
  resources:
    limits:
      cpu: 200m
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 32Mi
odk:
  replicas: 1
  existingSecret: ""
  secrets:
    DB_HOST: ""
    DB_NAME: ""
    DB_PASSWORD: ""
    DB_USER: ""
    DOMAIN: odkcentral.k8s.tinonet.nl
    EMAIL_FROM: odkcentral@yourdomain.tld
    EMAIL_HOST: ""
    EMAIL_PASSWORD: ""
    EMAIL_PORT: 587
    EMAIL_SECURE: "true"
    EMAIL_USER: ""
    ENKETO_API_KEY: enketo_api_key_secret
    ENKETO_LESS_SECRET: enketo_less_secret
    ENKETO_SECRET: enketo_secret
    PGSSLMODE: "true"
    SSL_TYPE: upstream
    OIDC_ENABLED: true
    OIDC_ISSUER_URL: ""
    OIDC_CLIENT_ID: ""
    OIDC_CLIENT_SECRET: ""
    OIDC_ENABLED: "false"
    OIDC_CLIENT_ID: ""
    OIDC_CLIENT_SECRET: ""
    OIDC_ISSUER_URL: ""
    S3_SERVER: ""
    S3_ACCESS_KEY: ""
    S3_SECRET_KEY: ""
    S3_BUCKET_NAME: ""
    DB_SSL: "true"
  user:
    existingSecret: ""
    password: admin12345678
    username: admin@yourdomain.tld
postfix:
  enabled: true
  overwriteFrom: ODK Sandbox <noreply@odkcentral.yourdomain.tld>
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  serverHostname: postfix.k8s.tinonet.nl
postgresql:
  architecture: standalone
  auth:
    database: odkcentral
    enablePostgresUser: true
    password: odkcentral
    username: odkcentral
  backups:
    bucketAccessKeyId: ""
    bucketEndpoint: https://s3.yourdomain.tld
    bucketLifeCycle: 30
    bucketName: ""
    bucketPath: ""
    bucketSecretAccessKey: ""
    enabled: false
    existingSecret: ""
    keepJobs: 1
    resources: {}
    schedule: 37 03 * * *
  clusterDomain: cluster.local
  enabled: true
  global:
    imageRegistry: docker.io
  global.defaultStorageClass: default
  image:
    digest: ""
    repository: bitnamilegacy/postgresql
  metrics:
    enabled: false
  networkPolicy:
    enabled: true
  primary:
    persistence:
      size: 5Gi
    resources:
      limits:
        cpu: 750m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  readReplicas:
    persistence:
      size: 5Gi
    replicaCount: 1
    resources:
      limits:
        cpu: 750m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
pyxform:
  image: pyxform-http:v4.4.1
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 256Mi
redis:
  cache:
    resources:
      limits:
        cpu: 200m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 32Mi
  image: redis:8.6.2
  main:
    resources:
      limits:
        cpu: 200m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 32Mi
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 500Mi
    storageClass: default
service:
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 500Mi
    storageClass: default
  resources:
    limits:
      cpu: 500m
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 256Mi
